#!/bin/bash

TEMPLATE_DIR=$(dirname $(realpath $0))

TEMPLATE=std

# function to generate templates.
gen_template() {
    cp -r $TEMPLATE_DIR/templates/$TEMPLATE $1
    cd $1
    pwd
    [ -f template.tex ] && mv template.tex $1.tex
    [ -f template.md ] && mv template.md $1.md
    [ -f template.bib ] && mv template.bib $1.bib
    for F in $(ls -A); do
        if [ -d $F ]; then
            continue
        fi
        case $OSTYPE in
            darwin*)
                sed -i '' "s/template/$1/g" $F
            ;;
            linux*)
                sed -i "s/template/$1/g" $F
            ;;
        esac
    done
    cd ..
}

get_manual() {
    less $TEMPLATE_DIR/readme.txt
}

echo $@
for arg in $@; do
    case $arg in 
        -h)
            get_manual
            exit
        ;;
        -std)
            TEMPLATE=std
        ;;
        -md)
            TEMPLATE=md
        ;;
        -stat)
            TEMPLATE=stat
        ;;
        -essay)
            TEMPLATE=essay
        ;;
        *)
            echo "generating $arg from template $TEMPLATE"
            gen_template $arg
        ;;
    esac
done
